# syntax=docker/dockerfile:1

####

FROM cxx-swift

ARG DEBIAN_FRONTEND="noninteractive"

USER root
RUN apt -y update && apt -y install git

USER rust-user
RUN rustup self update
RUN rustup update
RUN rustup toolchain install nightly
